---
# tasks file for aws-vpc
- name: aws-vpc | Create VPC
  ec2_vpc_net:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    region: "{{ aws_default_region }}"
    name: "{{ env }}-kubernetes-vpc"
    cidr_block: "{{ aws_vpc.cidr_block }}"
    dns_hostnames: yes
    dns_support: yes
    multi_ok: no
    tags:
      Name: "{{ env }}-kubernetes-vpc"
      Environment: "{{ env }}"
  register: aws_vpc_result

- name: aws-vpc | Register VPC Id
  set_fact:
    aws_vpc_id: "{{ aws_vpc_result.vpc.id }}"
